name: lingshu
channels:
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.1
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cpuonly=2.0
  - cpython=3.10.18
  - ffmpeg=4.4.2
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - jinja2=3.1.6
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.24
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libsqlite=3.50.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.4.2
  - numpy=2.2.6
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openssl=3.5.2
  - p11-kit=0.24.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.18
  - python_abi=3.10
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.4
  - setuptools=80.9.0
  - svt-av1=1.4.1
  - tbb=2021.13.0
  - tk=8.6.13
  - typing_extensions=4.14.1
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - yaml=0.2.5
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - airportsdata==20250706
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - ascii-colors==0.11.4
      - astor==0.8.1
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==25.3.0
      - av==14.4.0
      - babel==2.17.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.46.0
      - blake3==1.0.5
      - bleach==6.2.0
      - boto3==1.39.16
      - botocore==1.39.16
      - brotli==1.1.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.6.15
      - cfgv==3.4.0
      - chromadb==1.0.13
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - comm==0.2.2
      - compressed-tensors==0.10.2
      - configparser==7.2.0
      - contourpy==1.3.2
      - cryptography==45.0.5
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==4.0.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - deepspeed==0.18.1
      - defusedxml==0.7.1
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.7.0
      - doclayout-yolo==0.0.4
      - dotenv==0.9.9
      - durationpy==0.10
      - easydict==1.13
      - einops==0.8.1
      - email-validator==2.2.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - facexlib==0.3.0
      - faiss-gpu==1.7.2
      - fast-langdetect==0.2.5
      - fastapi==0.116.0
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.2
      - fastjsonschema==2.21.1
      - fastrlock==0.8.3
      - fasttext-predict==0.9.2.4
      - ffmpy==0.6.1
      - filterpy==1.4.5
      - flash-attn==2.8.0.post2
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - future==1.0.0
      - gast==0.6.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.25.1
      - google-api-python-client==2.173.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.70.0
      - gradio==5.38.2
      - gradio-client==1.11.0
      - gradio-pdf==0.0.22
      - greenlet==3.2.3
      - groovy==0.1.2
      - grpcio==1.73.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - icecream==2.1.5
      - identify==2.6.12
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - interegular==0.3.3
      - ipykernel==6.29.5
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.1
      - json-repair==0.48.0
      - json5==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - keras==3.11.1
      - kiwisolver==1.4.8
      - kubernetes==33.1.0
      - langchain==0.3.26
      - langchain-community==0.3.26
      - langchain-core==0.3.66
      - langchain-text-splitters==0.3.8
      - langsmith==0.4.2
      - lark==1.2.2
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightrag-hku==1.4.4
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - lmdb==1.7.2
      - loguru==0.7.3
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mathruler==0.1.0
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mineru==2.1.9
      - mistral-common==1.7.0
      - mistune==3.1.3
      - ml-dtypes==0.5.3
      - mmh3==5.1.0
      - modelscope==1.28.1
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.5.1
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - nano-vectordb==0.0.4.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.13.0
      - nltk==3.9.1
      - nodeenv==1.9.1
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - numba==0.61.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - onnx==1.18.0
      - onnx-ir==0.1.5
      - onnx2tf==1.28.2
      - onnxruntime==1.22.0
      - onnxruntime-genai==0.9.0
      - onnxscript==0.1.0
      - onnxsim==0.4.36
      - open-clip-torch==2.32.0
      - openai==1.90.0
      - openai-clip==1.0.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-otlp-proto-common==1.34.1
      - opentelemetry-exporter-otlp-proto-grpc==1.34.1
      - opentelemetry-proto==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - opt-einsum==3.4.0
      - optimum==1.27.0
      - optree==0.17.0
      - orjson==3.10.18
      - outlines==0.1.11
      - outlines-core==0.1.26
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post6
      - pdfminer-six==20250506
      - pdftext==0.6.3
      - peft==0.17.1
      - pexpect==4.9.0
      - pillow==11.0.0
      - pip==25.3
      - pipmaster==0.9.2
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - posthog==5.4.0
      - pre-commit==4.2.0
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.1
      - pybind11==3.0.0
      - pyclipper==1.3.0.post6
      - pycountry==24.6.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pyiqa==0.1.14.1
      - pylatexenc==2.10
      - pyparsing==3.2.3
      - pypdf==5.9.0
      - pypdfium2==4.30.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pytest==8.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyuca==1.2
      - pyzmq==27.0.0
      - qwen-vl-utils==0.0.11
      - raganything==1.2.5
      - rapid-table==1.0.5
      - ray==2.47.1
      - referencing==0.36.2
      - regex==2024.11.6
      - reportlab==4.4.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rich-toolkit==0.14.8
      - rignore==0.5.1
      - robust-downloader==0.0.2
      - rouge==1.0.1
      - rpds-py==0.25.1
      - rsa==4.9.1
      - ruff==0.12.4
      - s3transfer==0.13.1
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.32.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - simsimd==6.5.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.5.2
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - stack-data==0.6.3
      - starlette==0.46.2
      - stringzilla==3.12.5
      - sympy==1.13.3
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - terminado==0.18.1
      - tf-keras==2.19.0
      - tflite-support==0.4.4
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.9.0
      - timm==1.0.15
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==3.3.0
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ultralytics==8.3.170
      - ultralytics-thop==2.0.14
      - uri-template==1.3.0
      - uritemplate==4.2.0
      - uvicorn==0.34.3
      - uvloop==0.21.0
      - virtualenv==20.31.2
      - vllm==0.9.2
      - wandb==0.22.3
      - watchfiles==1.1.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xformers==0.0.30
      - xgrammar==0.1.19
      - xlsxwriter==3.2.5
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.20.1
      - zipp==3.23.0
      - zstandard==0.23.0
